[2022-07-18 20:40:01,379] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: MIRR_MD_ACCOUNT_D.load_mirror_md_account_d scheduled__2022-07-18T20:35:00+00:00 [queued]>
[2022-07-18 20:40:01,388] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: MIRR_MD_ACCOUNT_D.load_mirror_md_account_d scheduled__2022-07-18T20:35:00+00:00 [queued]>
[2022-07-18 20:40:01,389] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 20:40:01,389] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-07-18 20:40:01,389] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 20:40:01,399] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): load_mirror_md_account_d> on 2022-07-18 20:35:00+00:00
[2022-07-18 20:40:01,402] {standard_task_runner.py:52} INFO - Started process 455 to run task
[2022-07-18 20:40:01,405] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MIRR_MD_ACCOUNT_D', 'load_mirror_md_account_d', 'scheduled__2022-07-18T20:35:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/mirror_calc.py', '--cfg-path', '/tmp/tmph66gkzbp', '--error-file', '/tmp/tmp2ry7pc0e']
[2022-07-18 20:40:01,406] {standard_task_runner.py:77} INFO - Job 11: Subtask load_mirror_md_account_d
[2022-07-18 20:40:01,458] {logging_mixin.py:109} INFO - Running <TaskInstance: MIRR_MD_ACCOUNT_D.load_mirror_md_account_d scheduled__2022-07-18T20:35:00+00:00 [running]> on host c002fdbc1111
[2022-07-18 20:40:01,512] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MIRR_MD_ACCOUNT_D
AIRFLOW_CTX_TASK_ID=load_mirror_md_account_d
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T20:35:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T20:35:00+00:00
[2022-07-18 20:40:01,514] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-18 20:40:01,514] {subprocess.py:74} INFO - Running command: ['bash', '-c', '"${SPARK_HOME}/bin/spark-submit" --master spark://spark:7077 spark_scripts/mirr_md_account_d.py']
[2022-07-18 20:40:01,522] {subprocess.py:85} INFO - Output:
[2022-07-18 20:40:02,804] {subprocess.py:89} INFO - 22/07/18 20:40:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-07-18 20:40:02,983] {subprocess.py:89} INFO - python3: can't open file '/tmp/***tmpscfr8ofn/spark_scripts/mirr_md_account_d.py': [Errno 2] No such file or directory
[2022-07-18 20:40:02,989] {subprocess.py:89} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2022-07-18 20:40:02,989] {subprocess.py:89} INFO - log4j:WARN Please initialize the log4j system properly.
[2022-07-18 20:40:02,989] {subprocess.py:89} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2022-07-18 20:40:03,022] {subprocess.py:93} INFO - Command exited with return code 2
[2022-07-18 20:40:03,034] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-07-18 20:40:03,040] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=MIRR_MD_ACCOUNT_D, task_id=load_mirror_md_account_d, execution_date=20220718T203500, start_date=20220718T204001, end_date=20220718T204003
[2022-07-18 20:40:03,052] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task load_mirror_md_account_d
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-07-18 20:40:03,094] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-18 20:40:03,123] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
