[2022-07-19 13:30:01,942] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: MIRR_MD_ACCOUNT_D.load_mirror_md_account_d scheduled__2022-07-19T13:25:00+00:00 [queued]>
[2022-07-19 13:30:01,949] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: MIRR_MD_ACCOUNT_D.load_mirror_md_account_d scheduled__2022-07-19T13:25:00+00:00 [queued]>
[2022-07-19 13:30:01,949] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 13:30:01,949] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-07-19 13:30:01,949] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 13:30:01,957] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): load_mirror_md_account_d> on 2022-07-19 13:25:00+00:00
[2022-07-19 13:30:01,960] {standard_task_runner.py:52} INFO - Started process 220 to run task
[2022-07-19 13:30:01,963] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MIRR_MD_ACCOUNT_D', 'load_mirror_md_account_d', 'scheduled__2022-07-19T13:25:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/mirror_calc.py', '--cfg-path', '/tmp/tmpf1ircj70', '--error-file', '/tmp/tmp0qyvvzzq']
[2022-07-19 13:30:01,963] {standard_task_runner.py:77} INFO - Job 28: Subtask load_mirror_md_account_d
[2022-07-19 13:30:02,004] {logging_mixin.py:109} INFO - Running <TaskInstance: MIRR_MD_ACCOUNT_D.load_mirror_md_account_d scheduled__2022-07-19T13:25:00+00:00 [running]> on host 0d52133e3a92
[2022-07-19 13:30:02,043] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MIRR_MD_ACCOUNT_D
AIRFLOW_CTX_TASK_ID=load_mirror_md_account_d
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T13:25:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T13:25:00+00:00
[2022-07-19 13:30:02,043] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-19 13:30:02,044] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ssh root@spark -p 8080 spark-submit --master spark://spark:7077 /usr/local/spark/core/mirr_md_account_d.py']
[2022-07-19 13:30:02,051] {subprocess.py:85} INFO - Output:
[2022-07-19 13:30:02,059] {subprocess.py:89} INFO - ssh_exchange_identification: Connection closed by remote host
[2022-07-19 13:30:02,060] {subprocess.py:93} INFO - Command exited with return code 255
[2022-07-19 13:30:02,069] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2022-07-19 13:30:02,075] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=MIRR_MD_ACCOUNT_D, task_id=load_mirror_md_account_d, execution_date=20220719T132500, start_date=20220719T133001, end_date=20220719T133002
[2022-07-19 13:30:02,085] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task load_mirror_md_account_d
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2022-07-19 13:30:02,098] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-19 13:30:02,122] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
