[2022-07-18 13:42:24,906] {processor.py:163} INFO - Started process (PID=70) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:24,907] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:42:24,908] {logging_mixin.py:109} INFO - [2022-07-18 13:42:24,908] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:24,950] {logging_mixin.py:109} INFO - [2022-07-18 13:42:24,950] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:42:25,945] {logging_mixin.py:109} INFO - [2022-07-18 13:42:25,941] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:42:25,955] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:25,955] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:25,976] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 1.079 seconds
[2022-07-18 13:42:56,017] {processor.py:163} INFO - Started process (PID=123) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:56,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:42:56,019] {logging_mixin.py:109} INFO - [2022-07-18 13:42:56,019] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:56,037] {logging_mixin.py:109} INFO - [2022-07-18 13:42:56,037] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:42:56,369] {logging_mixin.py:109} INFO - [2022-07-18 13:42:56,368] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:42:56,372] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:42:56,384] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.369 seconds
[2022-07-18 13:43:26,706] {processor.py:163} INFO - Started process (PID=186) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:43:26,707] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:43:26,708] {logging_mixin.py:109} INFO - [2022-07-18 13:43:26,708] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:43:26,737] {logging_mixin.py:109} INFO - [2022-07-18 13:43:26,737] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:43:27,117] {logging_mixin.py:109} INFO - [2022-07-18 13:43:27,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:43:27,120] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:43:27,127] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.424 seconds
[2022-07-18 13:43:57,528] {processor.py:163} INFO - Started process (PID=241) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:43:57,530] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:43:57,530] {logging_mixin.py:109} INFO - [2022-07-18 13:43:57,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:43:57,549] {logging_mixin.py:109} INFO - [2022-07-18 13:43:57,549] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:43:57,970] {logging_mixin.py:109} INFO - [2022-07-18 13:43:57,969] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:43:57,973] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:43:57,979] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.454 seconds
[2022-07-18 13:44:28,021] {processor.py:163} INFO - Started process (PID=304) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:44:28,022] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:44:28,022] {logging_mixin.py:109} INFO - [2022-07-18 13:44:28,022] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:44:28,042] {logging_mixin.py:109} INFO - [2022-07-18 13:44:28,042] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:44:28,431] {logging_mixin.py:109} INFO - [2022-07-18 13:44:28,430] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:44:28,435] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:44:28,441] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.424 seconds
[2022-07-18 13:44:59,495] {processor.py:163} INFO - Started process (PID=367) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:44:59,497] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:44:59,497] {logging_mixin.py:109} INFO - [2022-07-18 13:44:59,497] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:44:59,524] {logging_mixin.py:109} INFO - [2022-07-18 13:44:59,524] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:44:59,870] {logging_mixin.py:109} INFO - [2022-07-18 13:44:59,869] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:44:59,873] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:44:59,879] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.386 seconds
[2022-07-18 13:45:30,853] {processor.py:163} INFO - Started process (PID=421) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:45:30,854] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:45:30,855] {logging_mixin.py:109} INFO - [2022-07-18 13:45:30,855] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:45:30,892] {logging_mixin.py:109} INFO - [2022-07-18 13:45:30,892] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:45:31,271] {logging_mixin.py:109} INFO - [2022-07-18 13:45:31,270] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:45:31,275] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:45:31,282] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.435 seconds
[2022-07-18 13:46:02,285] {processor.py:163} INFO - Started process (PID=485) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:46:02,291] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:46:02,291] {logging_mixin.py:109} INFO - [2022-07-18 13:46:02,291] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:46:02,314] {logging_mixin.py:109} INFO - [2022-07-18 13:46:02,314] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:46:02,673] {logging_mixin.py:109} INFO - [2022-07-18 13:46:02,673] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:46:02,676] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:46:02,682] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.400 seconds
[2022-07-18 13:46:33,682] {processor.py:163} INFO - Started process (PID=548) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:46:33,683] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:46:33,684] {logging_mixin.py:109} INFO - [2022-07-18 13:46:33,683] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:46:33,706] {logging_mixin.py:109} INFO - [2022-07-18 13:46:33,706] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:46:34,103] {logging_mixin.py:109} INFO - [2022-07-18 13:46:34,102] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:46:34,106] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:46:34,113] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.434 seconds
[2022-07-18 13:47:04,140] {processor.py:163} INFO - Started process (PID=611) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:47:04,141] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:47:04,142] {logging_mixin.py:109} INFO - [2022-07-18 13:47:04,142] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:47:04,161] {logging_mixin.py:109} INFO - [2022-07-18 13:47:04,161] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:47:04,540] {logging_mixin.py:109} INFO - [2022-07-18 13:47:04,539] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:47:04,544] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:47:04,551] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.414 seconds
[2022-07-18 13:47:34,584] {processor.py:163} INFO - Started process (PID=665) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:47:34,586] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:47:34,586] {logging_mixin.py:109} INFO - [2022-07-18 13:47:34,586] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:47:34,606] {logging_mixin.py:109} INFO - [2022-07-18 13:47:34,606] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:47:34,955] {logging_mixin.py:109} INFO - [2022-07-18 13:47:34,954] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:47:34,958] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:47:34,972] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.391 seconds
[2022-07-18 13:48:05,016] {processor.py:163} INFO - Started process (PID=728) to work on /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:48:05,017] {processor.py:642} INFO - Processing file /opt/airflow/dags/dm_fill_account_turnover.py for tasks to queue
[2022-07-18 13:48:05,018] {logging_mixin.py:109} INFO - [2022-07-18 13:48:05,018] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:48:05,037] {logging_mixin.py:109} INFO - [2022-07-18 13:48:05,037] {base.py:79} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: airflow, Password: airflow, extra: {}
[2022-07-18 13:48:05,421] {logging_mixin.py:109} INFO - [2022-07-18 13:48:05,420] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dm_fill_account_turnover.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dm_fill_account_turnover.py", line 5, in <module>
    from core import AIRFLOW_HOME, DEFAULT_POSTGRES_CONN_ID
  File "/usr/local/lib/python3.7/site-packages/core/__init__.py", line 6, in <module>
    from core.Mirror import Mirror
  File "/usr/local/lib/python3.7/site-packages/core/Mirror.py", line 2, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-18 13:48:05,424] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dm_fill_account_turnover.py
[2022-07-18 13:48:05,430] {processor.py:171} INFO - Processing /opt/airflow/dags/dm_fill_account_turnover.py took 0.417 seconds
