[2022-06-22 20:51:58,975] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: f101_from_csv_to_db.update_double_f101_dm_csv manual__2022-06-22T20:51:55.856736+00:00 [queued]>
[2022-06-22 20:51:58,983] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: f101_from_csv_to_db.update_double_f101_dm_csv manual__2022-06-22T20:51:55.856736+00:00 [queued]>
[2022-06-22 20:51:58,983] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 20:51:58,983] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-22 20:51:58,983] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 20:51:58,992] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): update_double_f101_dm_csv> on 2022-06-22 20:51:55.856736+00:00
[2022-06-22 20:51:58,996] {standard_task_runner.py:52} INFO - Started process 3789 to run task
[2022-06-22 20:51:58,999] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'f101_from_csv_to_db', 'update_double_f101_dm_csv', 'manual__2022-06-22T20:51:55.856736+00:00', '--job-id', '1145', '--raw', '--subdir', 'DAGS_FOLDER/f101_from_local.py', '--cfg-path', '/tmp/tmpek3r8gji', '--error-file', '/tmp/tmp7nxqtw16']
[2022-06-22 20:51:59,000] {standard_task_runner.py:77} INFO - Job 1145: Subtask update_double_f101_dm_csv
[2022-06-22 20:51:59,047] {logging_mixin.py:109} INFO - Running <TaskInstance: f101_from_csv_to_db.update_double_f101_dm_csv manual__2022-06-22T20:51:55.856736+00:00 [running]> on host bc39be91d060
[2022-06-22 20:51:59,093] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=f101_from_csv_to_db
AIRFLOW_CTX_TASK_ID=update_double_f101_dm_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-06-22T20:51:55.856736+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-22T20:51:55.856736+00:00
[2022-06-22 20:51:59,130] {FromLocal.py:52} INFO - Column from_date changed date-time format
[2022-06-22 20:51:59,130] {FromLocal.py:52} INFO - Column to_date changed date-time format
[2022-06-22 20:51:59,130] {FromLocal.py:58} INFO - Table dm_f101_round_f read in pandas success. 
[2022-06-22 20:51:59,163] {FromLocal.py:59} INFO - 
    from_date    to_date  ... balance_out_total  r_balance_out_total
0 2018-01-01 2018-01-31  ...        2796528.22                  NaN
1 2018-01-01 2018-01-31  ...              0.00                  NaN
2 2018-01-01 2018-01-31  ...         424336.82                  NaN
3 2018-01-01 2018-01-31  ...              0.00                  NaN
4 2018-01-01 2018-01-31  ...        1131304.48                  NaN

[5 rows x 29 columns]
[2022-06-22 20:51:59,195] {FromLocal.py:80} INFO - [Errno 2] No such file or directory: 'update_dm/f101_double_from_local.sql'
[2022-06-22 20:52:04,206] {python.py:175} INFO - Done. Returned value was: None
[2022-06-22 20:52:04,215] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=f101_from_csv_to_db, task_id=update_double_f101_dm_csv, execution_date=20220622T205155, start_date=20220622T205158, end_date=20220622T205204
[2022-06-22 20:52:04,247] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-22 20:52:04,271] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
