[2022-06-22 21:10:55,533] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: f101_from_csv_to_db.update_double_f101_dm_csv manual__2022-06-22T21:10:52.410781+00:00 [queued]>
[2022-06-22 21:10:55,551] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: f101_from_csv_to_db.update_double_f101_dm_csv manual__2022-06-22T21:10:52.410781+00:00 [queued]>
[2022-06-22 21:10:55,551] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 21:10:55,551] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-06-22 21:10:55,551] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-22 21:10:55,561] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): update_double_f101_dm_csv> on 2022-06-22 21:10:52.410781+00:00
[2022-06-22 21:10:55,565] {standard_task_runner.py:52} INFO - Started process 4667 to run task
[2022-06-22 21:10:55,568] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'f101_from_csv_to_db', 'update_double_f101_dm_csv', 'manual__2022-06-22T21:10:52.410781+00:00', '--job-id', '1153', '--raw', '--subdir', 'DAGS_FOLDER/f101_from_local.py', '--cfg-path', '/tmp/tmpjtb6zesy', '--error-file', '/tmp/tmp5_7q_8zo']
[2022-06-22 21:10:55,569] {standard_task_runner.py:77} INFO - Job 1153: Subtask update_double_f101_dm_csv
[2022-06-22 21:10:55,618] {logging_mixin.py:109} INFO - Running <TaskInstance: f101_from_csv_to_db.update_double_f101_dm_csv manual__2022-06-22T21:10:52.410781+00:00 [running]> on host bc39be91d060
[2022-06-22 21:10:55,682] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=f101_from_csv_to_db
AIRFLOW_CTX_TASK_ID=update_double_f101_dm_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-06-22T21:10:52.410781+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-22T21:10:52.410781+00:00
[2022-06-22 21:10:55,731] {FromLocal.py:52} INFO - Column from_date changed date-time format
[2022-06-22 21:10:55,732] {FromLocal.py:52} INFO - Column to_date changed date-time format
[2022-06-22 21:10:55,732] {FromLocal.py:58} INFO - Table dm_f101_round_f read in pandas success. 
[2022-06-22 21:10:55,764] {FromLocal.py:59} INFO - 
    from_date    to_date  ... balance_out_total  r_balance_out_total
0 2018-01-01 2018-01-31  ...        2796528.22                  NaN
1 2018-01-01 2018-01-31  ...              0.00                  NaN
2 2018-01-01 2018-01-31  ...         424336.82                  NaN
3 2018-01-01 2018-01-31  ...              0.00                  NaN
4 2018-01-01 2018-01-31  ...        1131304.48                  NaN

[5 rows x 29 columns]
[2022-06-22 21:10:55,825] {FromLocal.py:80} INFO - (psycopg2.errors.SyntaxError) syntax error at or near "DO"
LINE 5: DO UPDATE 
        ^

[SQL: INSERT INTO dm.dm_f101_round_f_v2
    SELECT DISTINCT *
    FROM temp.dm_f101_round_f       
ON CONFLICT ON CONSTRAINT 
DO UPDATE 
	SET
        FROM_DATE  = excluded.FROM_DATE,
        TO_DATE  = excluded.TO_DATE,
        CHAPTER	 = excluded.CHAPTER,
        LEDGER_ACCOUNT  = excluded.LEDGER_ACCOUNT,
        CHARACTERISTIC  = excluded.CHARACTERISTIC,
        BALANCE_IN_RUB  = excluded.BALANCE_IN_RUB,
        R_BALANCE_IN_RUB  = excluded.R_BALANCE_IN_RUB,
        BALANCE_IN_VAL  = excluded.BALANCE_IN_VAL,
        R_BALANCE_IN_VAL  = excluded.R_BALANCE_IN_VAL,
        BALANCE_IN_TOTAL  = excluded.BALANCE_IN_TOTAL,
        R_BALANCE_IN_TOTAL  = excluded.R_BALANCE_IN_TOTAL,
        TURN_DEB_RUB  = excluded.TURN_DEB_RUB,
        R_TURN_DEB_RUB  = excluded.R_TURN_DEB_RUB,
        TURN_DEB_VAL  = excluded.TURN_DEB_VAL,
        R_TURN_DEB_VAL  = excluded.R_TURN_DEB_VAL,
        TURN_DEB_TOTAL  = excluded.TURN_DEB_TOTAL,
        R_TURN_DEB_TOTAL  = excluded.R_TURN_DEB_TOTAL,
        TURN_CRE_RUB  = excluded.TURN_CRE_RUB,
        R_TURN_CRE_RUB  = excluded.R_TURN_CRE_RUB,
        TURN_CRE_VAL  = excluded.TURN_CRE_VAL,
        R_TURN_CRE_VAL  = excluded.R_TURN_CRE_VAL,
        TURN_CRE_TOTAL  = excluded.TURN_CRE_TOTAL,
        R_TURN_CRE_TOTAL  = excluded.R_TURN_CRE_TOTAL,
        BALANCE_OUT_RUB  = excluded.BALANCE_OUT_RUB,
        R_BALANCE_OUT_RUB  = excluded.R_BALANCE_OUT_RUB,
        BALANCE_OUT_VAL  = excluded.BALANCE_OUT_VAL,
        R_BALANCE_OUT_VAL  = excluded.R_BALANCE_OUT_VAL,
        BALANCE_OUT_TOTAL  = excluded.BALANCE_OUT_TOTAL,
        R_BALANCE_OUT_TOTAL  = excluded.R_BALANCE_OUT_TOTAL;]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2022-06-22 21:11:00,839] {python.py:175} INFO - Done. Returned value was: None
[2022-06-22 21:11:00,848] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=f101_from_csv_to_db, task_id=update_double_f101_dm_csv, execution_date=20220622T211052, start_date=20220622T211055, end_date=20220622T211100
[2022-06-22 21:11:00,870] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-22 21:11:00,899] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
