[2022-06-08 10:25:57,351] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: CSV_TO_DS.SEND_DS_ft_balance_f manual__2022-06-08T10:25:54.566651+00:00 [queued]>
[2022-06-08 10:25:57,362] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: CSV_TO_DS.SEND_DS_ft_balance_f manual__2022-06-08T10:25:54.566651+00:00 [queued]>
[2022-06-08 10:25:57,362] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 10:25:57,362] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-08 10:25:57,362] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 10:25:57,383] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): SEND_DS_ft_balance_f> on 2022-06-08 10:25:54.566651+00:00
[2022-06-08 10:25:57,387] {standard_task_runner.py:52} INFO - Started process 3773 to run task
[2022-06-08 10:25:57,390] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'CSV_TO_DS', 'SEND_DS_ft_balance_f', 'manual__2022-06-08T10:25:54.566651+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_ds.py', '--cfg-path', '/tmp/tmp_om1w4vx', '--error-file', '/tmp/tmp7nvgxzs1']
[2022-06-08 10:25:57,391] {standard_task_runner.py:80} INFO - Job 127: Subtask SEND_DS_ft_balance_f
[2022-06-08 10:25:57,461] {task_command.py:370} INFO - Running <TaskInstance: CSV_TO_DS.SEND_DS_ft_balance_f manual__2022-06-08T10:25:54.566651+00:00 [running]> on host 33a1fdf44d41
[2022-06-08 10:25:57,541] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CSV_TO_DS
AIRFLOW_CTX_TASK_ID=SEND_DS_ft_balance_f
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T10:25:54.566651+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-08T10:25:54.566651+00:00
[2022-06-08 10:25:57,550] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-06-08 10:25:57,579] {csv_to_ds.py:82} INFO - Column on_date changed date-time format
[2022-06-08 10:25:57,579] {csv_to_ds.py:88} INFO - Table ft_balance_f read in pandas success.
[2022-06-08 10:25:57,588] {csv_to_ds.py:89} INFO - 
      on_date  account_rk  currency_rk  balance_out
0 2017-12-31    36237725           35     38318.13
1 2017-12-31       24656           35     80533.62
2 2017-12-31    18849846           34     63891.96
3 2017-12-31     1972647           34     87732.10
4 2017-12-31    34157174           34     97806.90
[2022-06-08 10:25:57,588] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_to_ds.py", line 90, in send_csv_to_ds
    condition += e
UnboundLocalError: local variable 'e' referenced before assignment
[2022-06-08 10:25:57,596] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=CSV_TO_DS, task_id=SEND_DS_ft_balance_f, execution_date=20220608T102554, start_date=20220608T102557, end_date=20220608T102557
[2022-06-08 10:25:57,605] {standard_task_runner.py:97} ERROR - Failed to execute job 127 for task SEND_DS_ft_balance_f (local variable 'e' referenced before assignment; 3773)
[2022-06-08 10:25:57,648] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-08 10:25:57,699] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
