[2022-06-05 22:35:50,799] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: CSV_TO_DS.create_schema_and_tables manual__2022-06-05T22:30:47.677113+00:00 [queued]>
[2022-06-05 22:35:50,808] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: CSV_TO_DS.create_schema_and_tables manual__2022-06-05T22:30:47.677113+00:00 [queued]>
[2022-06-05 22:35:50,808] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-05 22:35:50,808] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-05 22:35:50,809] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-05 22:35:50,821] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_schema_and_tables> on 2022-06-05 22:30:47.677113+00:00
[2022-06-05 22:35:50,824] {standard_task_runner.py:52} INFO - Started process 642 to run task
[2022-06-05 22:35:50,830] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'CSV_TO_DS', 'create_schema_and_tables', 'manual__2022-06-05T22:30:47.677113+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_ds.py', '--cfg-path', '/tmp/tmpuzmxdnel', '--error-file', '/tmp/tmpg9gaeg3q']
[2022-06-05 22:35:50,830] {standard_task_runner.py:80} INFO - Job 15: Subtask create_schema_and_tables
[2022-06-05 22:35:50,879] {task_command.py:370} INFO - Running <TaskInstance: CSV_TO_DS.create_schema_and_tables manual__2022-06-05T22:30:47.677113+00:00 [running]> on host 1d689ce05a02
[2022-06-05 22:35:50,953] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CSV_TO_DS
AIRFLOW_CTX_TASK_ID=create_schema_and_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T22:30:47.677113+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-05T22:30:47.677113+00:00
[2022-06-05 22:35:50,971] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 186, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2022-06-05 22:35:50,974] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=CSV_TO_DS, task_id=create_schema_and_tables, execution_date=20220605T223047, start_date=20220605T223550, end_date=20220605T223550
[2022-06-05 22:35:50,983] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task create_schema_and_tables (The conn_id `postgres` isn't defined; 642)
[2022-06-05 22:35:51,010] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-05 22:35:51,050] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
