[2022-06-06 13:26:20,158] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: CSV_TO_DS.SEND_DS_ft_balance_f manual__2022-06-06T13:26:16.840805+00:00 [queued]>
[2022-06-06 13:26:20,176] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: CSV_TO_DS.SEND_DS_ft_balance_f manual__2022-06-06T13:26:16.840805+00:00 [queued]>
[2022-06-06 13:26:20,176] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 13:26:20,176] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 13:26:20,177] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 13:26:20,188] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): SEND_DS_ft_balance_f> on 2022-06-06 13:26:16.840805+00:00
[2022-06-06 13:26:20,192] {standard_task_runner.py:52} INFO - Started process 483 to run task
[2022-06-06 13:26:20,195] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'CSV_TO_DS', 'SEND_DS_ft_balance_f', 'manual__2022-06-06T13:26:16.840805+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_ds.py', '--cfg-path', '/tmp/tmpg1o55m74', '--error-file', '/tmp/tmpjwu5rqh5']
[2022-06-06 13:26:20,195] {standard_task_runner.py:80} INFO - Job 77: Subtask SEND_DS_ft_balance_f
[2022-06-06 13:26:20,271] {task_command.py:370} INFO - Running <TaskInstance: CSV_TO_DS.SEND_DS_ft_balance_f manual__2022-06-06T13:26:16.840805+00:00 [running]> on host 33a1fdf44d41
[2022-06-06 13:26:20,344] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=CSV_TO_DS
AIRFLOW_CTX_TASK_ID=SEND_DS_ft_balance_f
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T13:26:16.840805+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-06T13:26:16.840805+00:00
[2022-06-06 13:26:20,353] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-06-06 13:26:20,381] {csv_to_ds.py:44} INFO - Table ft_balance_f read in pandas success.
[2022-06-06 13:26:20,381] {csv_to_ds.py:45} INFO -    ACCOUNT_RK  CURRENCY_RK  BALANCE_OUT
0    36237725           35     38318.13
1       24656           35     80533.62
2    18849846           34     63891.96
3     1972647           34     87732.10
4    34157174           34     97806.90
[2022-06-06 13:26:20,425] {csv_to_ds.py:51} INFO - (psycopg2.errors.UndefinedColumn) column "index" of relation "ft_balance_f" does not exist
LINE 1: INSERT INTO ds.ft_balance_f (index, "ACCOUNT_RK", "CURRENCY_...
                                     ^

[SQL: INSERT INTO ds.ft_balance_f (index, "ACCOUNT_RK", "CURRENCY_RK", "BALANCE_OUT") VALUES (%(index)s, %(ACCOUNT_RK)s, %(CURRENCY_RK)s, %(BALANCE_OUT)s)]
[parameters: ({'index': 0, 'ACCOUNT_RK': 36237725, 'CURRENCY_RK': 35, 'BALANCE_OUT': 38318.13}, {'index': 1, 'ACCOUNT_RK': 24656, 'CURRENCY_RK': 35, 'BALANCE_OUT': 80533.62}, {'index': 2, 'ACCOUNT_RK': 18849846, 'CURRENCY_RK': 34, 'BALANCE_OUT': 63891.96}, {'index': 3, 'ACCOUNT_RK': 1972647, 'CURRENCY_RK': 34, 'BALANCE_OUT': 87732.1}, {'index': 4, 'ACCOUNT_RK': 34157174, 'CURRENCY_RK': 34, 'BALANCE_OUT': 97806.9}, {'index': 5, 'ACCOUNT_RK': 48829156, 'CURRENCY_RK': 34, 'BALANCE_OUT': 87620.47}, {'index': 6, 'ACCOUNT_RK': 13905, 'CURRENCY_RK': 34, 'BALANCE_OUT': 29554.0}, {'index': 7, 'ACCOUNT_RK': 17244, 'CURRENCY_RK': 34, 'BALANCE_OUT': 25852.49}  ... displaying 10 of 112 total bound parameter sets ...  {'index': 110, 'ACCOUNT_RK': 18007, 'CURRENCY_RK': 34, 'BALANCE_OUT': 58966.57}, {'index': 111, 'ACCOUNT_RK': 44195, 'CURRENCY_RK': 44, 'BALANCE_OUT': 3818.77})]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2022-06-06 13:26:20,426] {python.py:173} INFO - Done. Returned value was: None
[2022-06-06 13:26:20,444] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=CSV_TO_DS, task_id=SEND_DS_ft_balance_f, execution_date=20220606T132616, start_date=20220606T132620, end_date=20220606T132620
[2022-06-06 13:26:20,490] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-06 13:26:20,536] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
